#!/bin/bash
COMPUTERS="rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18"
for i in $COMPUTERS; do
	ping -c 1 "$i"
	RESULT=$?
	if  [ $RESULT -eq 0 ]; then
		echo "$i" online
	else
		echo "$i" offline
	fi
done
